# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '房间开盘'), (2, '车位开盘')], default=1, verbose_name='活动类型')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('phone_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='咨询电话')),
                ('test_start', models.DateTimeField(verbose_name='公测开始时间')),
                ('test_end', models.DateTimeField(verbose_name='公测结束时间')),
                ('test_price', models.BooleanField(default=False, verbose_name='是否显示公测放假')),
                ('event_start', models.DateTimeField(verbose_name='活动开始时间')),
                ('event_end', models.DateTimeField(verbose_name='活动结束时间')),
                ('limit', models.IntegerField(verbose_name='选房完成期限')),
                ('equ_login_num', models.IntegerField(verbose_name='支持设备登录数')),
                ('follow_num', models.IntegerField(verbose_name='同一账号允许收藏数')),
                ('login_msg', models.BooleanField(default=False, verbose_name='登录短信提醒')),
                ('price', models.BooleanField(default=False, verbose_name='是否显示原价')),
                ('covered_space', models.BooleanField(default=False, verbose_name='是否显示建筑面积')),
                ('covered_space_price', models.BooleanField(default=False, verbose_name='是否显示建筑面积单价')),
                ('inside_space', models.BooleanField(default=False, verbose_name='是否显示套内面积')),
                ('inside_space_price', models.BooleanField(default=False, verbose_name='是否显示套内面积单价')),
                ('description', models.TextField(verbose_name='活动细则')),
                ('notice', models.TextField(verbose_name='认购须知')),
                ('tip', models.TextField(verbose_name='温馨提示')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/%Y/%m/%d/', verbose_name='活动封面')),
                ('plane_graph', models.ImageField(blank=True, null=True, upload_to='planeGraph/%Y/%m/%d/', verbose_name='平面图')),
                ('term', models.TextField(verbose_name='协议')),
            ],
        ),
    ]
