# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '房间开盘'), (2, '车位开盘')], default=1, verbose_name='活动类型')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('phone_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='咨询电话')),
                ('test_start', models.DateTimeField(verbose_name='公测开始时间')),
                ('test_end', models.DateTimeField(verbose_name='公测结束时间')),
                ('test_price', models.BooleanField(default=False, verbose_name='是否显示公测房价')),
                ('event_start', models.DateTimeField(verbose_name='活动开始时间')),
                ('event_end', models.DateTimeField(verbose_name='活动结束时间')),
                ('limit', models.IntegerField(verbose_name='选房完成期限')),
                ('equ_login_num', models.IntegerField(verbose_name='支持设备登录数')),
                ('follow_num', models.IntegerField(verbose_name='同一账号允许收藏数')),
                ('covered_space', models.BooleanField(default=False, verbose_name='是否显示建筑面积')),
                ('covered_space_price', models.BooleanField(default=False, verbose_name='是否显示建筑面积单价')),
                ('description', models.TextField(verbose_name='活动细则')),
                ('notice', models.TextField(verbose_name='认购须知')),
                ('tip', models.TextField(verbose_name='温馨提示')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/%Y/%m/%d/', verbose_name='活动封面')),
                ('plane_graph', models.ImageField(blank=True, null=True, upload_to='planeGraph/%Y/%m/%d/', verbose_name='平面图')),
                ('termname', models.CharField(blank=True, max_length=100, null=True, verbose_name='协议名称')),
                ('term', models.TextField(blank=True, null=True, verbose_name='协议内容')),
                ('is_pub', models.BooleanField(default=False, verbose_name='是否发布')),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50, verbose_name='楼号')),
                ('unit', models.CharField(max_length=100, verbose_name='单元')),
                ('floor', models.CharField(max_length=100, verbose_name='楼层')),
                ('room_num', models.CharField(max_length=50, verbose_name='房号')),
                ('price', models.CharField(max_length=100, verbose_name='原价')),
                ('total', models.CharField(max_length=100, verbose_name='线上总价')),
                ('status', models.BooleanField(default=False, verbose_name='上架状态')),
                ('is_sold', models.BooleanField(default=False, verbose_name='是否被卖')),
                ('is_testsold', models.BooleanField(default=False, verbose_name='公测是否已售')),
                ('remark', models.TextField(blank=True, verbose_name='描述补充')),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventdetail/%Y/%m/%d/', verbose_name='图片')),
                ('num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('visit_num', models.IntegerField(default=0, verbose_name='访问热度')),
                ('is_delete', models.BooleanField(default=False)),
                ('looking', models.CharField(max_length=100, verbose_name='朝向')),
                ('term', models.CharField(max_length=50, verbose_name='使用年限')),
                ('area', models.CharField(max_length=50, verbose_name='建筑面积')),
                ('unit_price', models.CharField(max_length=100, verbose_name='面积单价')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt.Event', verbose_name='所属活动')),
            ],
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='户型名称')),
                ('pic', models.ImageField(upload_to='housetype/%Y/%m/%d/', verbose_name='户型照片')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='编号')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt.Event')),
            ],
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='house_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apt.HouseType'),
        ),
    ]
