# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=50, verbose_name='期/批')),
                ('building', models.CharField(max_length=50, verbose_name='楼号')),
                ('unit', models.CharField(max_length=100, verbose_name='单元')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('room_num', models.CharField(max_length=50, verbose_name='房号')),
                ('price', models.CharField(max_length=100, verbose_name='原价')),
                ('total', models.CharField(max_length=100, verbose_name='线上总价')),
                ('house_type', models.CharField(max_length=100, verbose_name='户型')),
                ('floor_area', models.CharField(max_length=50, verbose_name='建筑面积')),
                ('is_sold', models.BooleanField(default=False, verbose_name='是否被卖')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='termname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='协议名称'),
        ),
        migrations.AlterField(
            model_name='event',
            name='term',
            field=models.TextField(blank=True, null=True, verbose_name='协议内容'),
        ),
        migrations.AlterField(
            model_name='event',
            name='test_price',
            field=models.BooleanField(default=False, verbose_name='是否显示公测放价'),
        ),
    ]
