# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_pub',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
    ]
