# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='visit_num',
            field=models.IntegerField(default=0, verbose_name='访问热度'),
        ),
    ]
