# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='park_hous',
            field=models.CharField(max_length=50, null=True, verbose_name='车位房源'),
        ),
        migrations.AddField(
            model_name='event',
            name='rc_list',
            field=models.CharField(max_length=50, null=True, verbose_name='认筹名单'),
        ),
        migrations.AddField(
            model_name='event',
            name='termname',
            field=models.CharField(max_length=100, null=True, verbose_name='协议名称'),
        ),
        migrations.AlterField(
            model_name='event',
            name='term',
            field=models.TextField(verbose_name='协议内容'),
        ),
        migrations.AlterField(
            model_name='event',
            name='test_price',
            field=models.BooleanField(default=False, verbose_name='是否显示公测放价'),
        ),
    ]
