# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0002_event_is_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='on_sale',
            field=models.BooleanField(default=False, verbose_name='是否上架'),
        ),
    ]
