# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0002_auto_20170719_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='price',
            field=models.CharField(max_length=100, verbose_name='总价'),
        ),
    ]
