# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0002_eventdetail_visit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='floor',
            field=models.CharField(max_length=100, verbose_name='楼层'),
        ),
    ]
