# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0002_auto_20170706_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100, verbose_name='楼栋')),
                ('unit', models.CharField(max_length=100, verbose_name='单元')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('room_num', models.CharField(max_length=100, verbose_name='房号')),
                ('price', models.CharField(max_length=100, verbose_name='原价')),
                ('total', models.CharField(max_length=100, verbose_name='线上总价')),
            ],
        ),
    ]
