# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0003_auto_20170712_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='户型名称')),
                ('pic', models.ImageField(upload_to='', verbose_name='户型照片')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt.Event')),
            ],
        ),
    ]
