# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0003_eventdetail_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
    ]
