# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0003_auto_20170712_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='on_sale',
        ),
    ]
