# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('apt', '0003_auto_20170720_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign', to='accounts.Customer'),
        ),
    ]
