# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0003_eventdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='park_hous',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rc_list',
        ),
        migrations.AlterField(
            model_name='event',
            name='term',
            field=models.TextField(blank=True, null=True, verbose_name='协议内容'),
        ),
        migrations.AlterField(
            model_name='event',
            name='termname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='协议名称'),
        ),
    ]
