# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0004_eventdetail_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='term',
        ),
        migrations.RemoveField(
            model_name='event',
            name='termname',
        ),
        migrations.RemoveField(
            model_name='eventdetail',
            name='is_delete',
        ),
    ]
