# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0004_housetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='pic',
            field=models.ImageField(upload_to='housetype/%Y/%m/%d/', verbose_name='户型照片'),
        ),
    ]
