# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0004_auto_20170707_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='status',
            field=models.BooleanField(default=False, verbose_name='上架状态'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='building',
            field=models.CharField(max_length=50, verbose_name='楼号'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='floor',
            field=models.IntegerField(max_length=50, verbose_name='楼层'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='room_num',
            field=models.CharField(max_length=50, verbose_name='房号'),
        ),
    ]
