# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0005_auto_20170720_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='house_limit',
            field=models.CharField(default=1, max_length=100, verbose_name='房源数量限制'),
            preserve_default=False,
        ),
    ]
