# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0005_auto_20170707_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apt.Event', verbose_name='所属活动'),
            preserve_default=False,
        ),
    ]
