# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0005_auto_20170711_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='term',
            field=models.TextField(blank=True, null=True, verbose_name='协议内容'),
        ),
        migrations.AddField(
            model_name='event',
            name='termname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='协议名称'),
        ),
    ]
