# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0005_auto_20170712_1953'),
        ('apt', '0004_remove_eventdetail_on_sale'),
    ]

    operations = [
    ]
