# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0006_eventdetail_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eventdetail/%Y/%m/%d/', verbose_name='平面图'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='是否被卖'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
