# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0006_merge_20170713_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='housetype',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eventdetail/%Y/%m/%d/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='num',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
    ]
