# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0007_auto_20170708_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='remark',
            field=models.TextField(blank=True, verbose_name='描述补充'),
        ),
    ]
