# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0007_auto_20170713_1004'),
        ('apt', '0006_merge_20170713_0833'),
    ]

    operations = [
    ]
