# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0007_auto_20170726_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='area',
            field=models.FloatField(max_length=50, verbose_name='建筑面积'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='unit_price',
            field=models.FloatField(max_length=100, verbose_name='面积单价'),
        ),
    ]
