# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0007_auto_20170713_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
