# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0008_auto_20170711_1448'),
        ('apt', '0006_auto_20170711_1448'),
    ]

    operations = [
    ]
