# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0009_auto_20170728_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='house_limit',
        ),
        migrations.AlterField(
            model_name='event',
            name='plane_graph',
            field=models.ImageField(blank=True, null=True, storage=system.storage.ImageStorage(), upload_to='planeGraph/%Y/%m/%d/', verbose_name='平面图'),
        ),
    ]
