# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0009_merge_20170712_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='term',
            field=models.TextField(blank=True, null=True, verbose_name='协议内容'),
        ),
        migrations.AddField(
            model_name='event',
            name='termname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='协议名称'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='is_testsold',
            field=models.BooleanField(default=False, verbose_name='公测是否已售'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='num',
            field=models.IntegerField(null=True, verbose_name='收藏人数'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='floor',
            field=models.IntegerField(verbose_name='楼层'),
        ),
    ]
