# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0009_merge_20170713_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='house_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apt.HouseType'),
        ),
    ]
