# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0010_eventdetail_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='area',
            field=models.CharField(default=200, max_length=50, verbose_name='建筑面积'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='looking',
            field=models.CharField(default='东', max_length=100, verbose_name='朝向'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='term',
            field=models.CharField(default=70, max_length=50, verbose_name='使用年限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='unit_price',
            field=models.CharField(default=20000, max_length=100, verbose_name='面积单价'),
            preserve_default=False,
        ),
    ]
