# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0010_auto_20170731_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='term',
            field=models.IntegerField(verbose_name='使用年限'),
        ),
    ]
