# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0010_auto_20170711_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='is_delete',
        ),
    ]
