# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0011_remove_eventdetail_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_pub',
        ),
        migrations.RemoveField(
            model_name='event',
            name='term',
        ),
        migrations.RemoveField(
            model_name='event',
            name='termname',
        ),
    ]
