# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0011_remove_eventdetail_is_delete'),
        ('apt', '0006_auto_20170711_1448'),
    ]

    operations = [
    ]
