# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0012_auto_20170801_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='plane_graph3',
            field=models.ImageField(blank=True, null=True, storage=system.storage.ImageStorage(), upload_to='planeGraph3/%Y/%m/%d/', verbose_name='平面图3'),
        ),
    ]
