# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0013_event_plane_graph3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='equ_login_num',
            field=models.IntegerField(default=1, verbose_name='支持设备登录数'),
        ),
    ]
