# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0014_auto_20170802_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='visit_num',
        ),
    ]
