# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0015_remove_eventdetail_visit_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='type',
            field=models.CharField(default='暂无数据', max_length=50, verbose_name='户型名称'),
        ),
    ]
