# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0017_remove_housetype_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='event',
            name='covered_space',
            field=models.BooleanField(default=True, verbose_name='是否显示建筑面积'),
        ),
        migrations.AlterField(
            model_name='event',
            name='covered_space_price',
            field=models.BooleanField(default=True, verbose_name='是否显示建筑面积单价'),
        ),
        migrations.AlterField(
            model_name='event',
            name='test_price',
            field=models.BooleanField(default=True, verbose_name='是否显示公测房价'),
        ),
    ]
