# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0018_auto_20170806_1706'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventdetail',
            unique_together=set([('building', 'unit', 'floor', 'room_num', 'event')]),
        ),
    ]
