# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
        ('apt', '0019_auto_20170807_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backstage.City'),
        ),
        migrations.AddField(
            model_name='company',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='账号过期日期'),
        ),
        migrations.AddField(
            model_name='company',
            name='house_limit',
            field=models.IntegerField(default=0, verbose_name='房源数量限制'),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backstage.Province'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='昵称'),
        ),
    ]
