# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0020_auto_20170816_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='looking',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='朝向'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='户型名称'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单元'),
        ),
    ]
