# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='custom',
            new_name='customer',
        ),
    ]
