# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='count',
            field=models.IntegerField(default=1, verbose_name='可选套数'),
        ),
    ]
