# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0004_eventdetail_is_delete'),
        ('accounts', '0002_auto_20170710_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='公测订单时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt.Event')),
                ('eventdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt.EventDetail')),
            ],
        ),
    ]
