# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170728_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='house_limit',
            field=models.IntegerField(default=0, verbose_name='房源数量限制'),
        ),
    ]
