# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0008_auto_20170709_0853'),
        ('accounts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('identication', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt.Event')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='custom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Custom'),
        ),
    ]
