# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170712_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='testroom',
        ),
        migrations.AlterField(
            model_name='customer',
            name='count',
            field=models.IntegerField(default=0, verbose_name='可选套数'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt.Event', verbose_name='关联活动'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='heat',
            field=models.IntegerField(default=0, verbose_name='访问热度'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='protime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='同意协议时间'),
        ),
    ]
