# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_house_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='账号过期日期'),
        ),
    ]
