# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170712_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
