# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170709_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='custom',
            name='identication',
            field=models.CharField(max_length=50, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='realname',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
