# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170709_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custom',
            new_name='Customer',
        ),
    ]
