# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_is_delete'),
        ('accounts', '0004_auto_20170713_1519'),
    ]

    operations = [
    ]
