# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_session_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('user', 'is_test')]),
        ),
    ]
