# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20170713_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='订单时间'),
        ),
    ]
