# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170713_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.CharField(default='', max_length=100, verbose_name='订单编号'),
            preserve_default=False,
        ),
    ]
