# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0018_auto_20170806_1706'),
        ('accounts', '0006_auto_20170804_1548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('mobile', 'identication', 'event')]),
        ),
    ]
