# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0019_auto_20170807_1040'),
        ('accounts', '0007_auto_20170807_0908'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('eventdetail', 'is_test')]),
        ),
    ]
