# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170807_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='house_limit',
        ),
    ]
