# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0020_auto_20170815_1700'),
        ('accounts', '0008_auto_20170815_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apt.Client'),
        ),
    ]
