# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170816_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consultant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='置业顾问'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='顾问电话'),
        ),
    ]
