# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170821_0839'),
        ('accounts', '0008_auto_20170822_1047'),
    ]

    operations = [
    ]
